FOLDER: '/scratch/aparna/experiments' # Experiment files saving path

TEST:
  FOLDER: '/scratch/aparna/results' # Testing files saving path

DATASET:
  SMPL_PATH: '/scratch/aparna/deps/smpl'
  TRANSFORM_PATH: '/scratch/aparna/deps/transforms/'
  WORD_VERTILIZER_PATH: '/scratch/aparna/deps/glove/'
  UNIMOCAP:
    ROOT: './datasets/UniMocap' # KIT directory
    SPLIT_ROOT: './datasets/UniMocap' # KIT splits directory
  KIT:
    ROOT: './datasets/kit-ml' # KIT directory
    SPLIT_ROOT: './datasets/kit-ml' # KIT splits directory
  HUMANML3D:
    ROOT: './datasets/humanml3d' # HumanML3D directory
    SPLIT_ROOT: './datasets/humanml3d' # HumanML3D splits directory
  HUMANACT12:
    ROOT: ./datasets/HumanAct12Poses
    SPLIT_ROOT: ./datasets/HumanAct12Poses
  UESTC:
    ROOT: ./datasets/uestc
    SPLIT_ROOT: ./datasets/uestc
  AMASS:
    DB_ROOT: /apdcephfs/share_1227775/shingxchen/uicap/data/vibe_db
  MOTIONX:
    ROOT: ./datasets/Motion-X
    SPLIT_ROOT: ./datasets/Motion-X/split
    SEMANTIC_TEXT_ROOT: ./datasets/Motion-X/texts/semantic_texts
    FACE_TEXT_ROOT: ./datasets/Motion-X/texts/face_texts
  
  BSL:
    ROOT: /scratch/aparna/BSL_t2m_test_ready
    SPLIT_ROOT: /scratch/aparna/BSL_t2m_test_ready
    SEMANTIC_TEXT_ROOT: /scratch/aparna/BSL_t2m_test_ready/texts/semantic_texts
    FACE_TEXT_ROOT: /scratch/aparna/BSL_t2m_test_ready/texts/face
  
  ASL:
    ROOT: /scratch/aparna/ASL_t2m
    SPLIT_ROOT: /scratch/aparna/ASL_t2m
    SEMANTIC_TEXT_ROOT: /scratch/aparna/ASL_t2m/texts/semantic_texts
    FACE_TEXT_ROOT: /scratch/aparna/ASL_t2m/texts/face



model:
  bert_path: '/scratch/aparna/deps/distilbert-base-uncased' # bert model path for all text encoders
  clip_path: '/scratch/aparna/deps/clip-vit-large-patch14' # bert model path for all text encoders
  t2m_path: '/scratch/aparna/deps/t2m/'

  humanact12_rec_path: './deps/actionrecognition'
  uestc_rec_path: './deps/actionrecognition'

RENDER:
  BLENDER_PATH: '/apdcephfs/share_1227775/mingzhenzhu/jiangbiao/libs/blender-2.93.2-linux-x64/blender'
  FACES_PATH: '/apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/deps/smplh/smplh.faces'
  FOLDER: ./animations
